### ISSUE TITLE
Wrong syntax coloring for string with trailing space in function call

### ISSUE THREAD

**Issue by tpwo** [SimplyDanny/modelica-language-vscode#7]
Hi, I noticed that syntax coloring is sometimes wrong for strings, e.g if you add a trailing space after `foo`:

![image](https://user-images.githubusercontent.com/49607727/142879952-932d7f7f-3af0-4a16-bda8-a0fa6d1300a4.png)

Removing space makes it work:

![image](https://user-images.githubusercontent.com/49607727/142880053-2d08ddc2-e5ca-489f-8c8d-cbfbdb7834fe.png)

But it won't work if you have two words with a space in between:

![image](https://user-images.githubusercontent.com/49607727/142881931-d720bd90-2800-4c13-a53c-6ca4f213028f.png)

---

I also noticed that the capitalization itself has some impact, e.g. it works fine with small `s` after `.`:

![image](https://user-images.githubusercontent.com/49607727/142881072-bddd1c14-eb15-46b5-b77e-19bd9ef74390.png)

But breaks if you make it `S`:

![image](https://user-images.githubusercontent.com/49607727/142881198-9f24adc4-d404-41b7-9589-a268d3ecabaf.png)

It seems that it starts treating it as a type (blue color) for some reason.

In VS Code, I'm using *Dark+ (default dark)* theme.

**Comment by SimplyDanny** [comment]
Thanks for the report! I'll try to fix the issues as soon as there is some time left.

**Comment by SimplyDanny** [comment]
I just noticed that your reported issues have already been fixed for a long time ([v0.0.4](https://github.com/SimplyDanny/modelica-language-vscode/releases/tag/v0.0.4)). They were but not published to Microsoft's marketplace, while on the [Open VSX Registry](https://open-vsx.org), version v0.0.4 had been available immediately. 

The reason was that Microsoft didn't allow me to access my Marketplace account for opaque reasons. Now that they grabbed even more of my personal data (for no clear reasons) I'm able to publish again. So an update of the extension to v0.0.4 should fix all the highlighting flaws you mentioned. Or you opt for the more developer-friendly and less data-hungry Open VSX Registry as an alternative extension source. 😉

**Comment by tpwo** [comment]
Thanks, I can confirm that I was able to download 0.0.4 directly from within VS Code, and it works like a charm!

Sorry to hear that about the Marketplace. I wasn't even aware of Open VSX Registry, so thank you for mentioning it.

But I'm afraid that most people also don't know it, so publishing any extension only there probably will cut down the user base a lot :/
